config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  root 'teachers#index'

   resources:teachers

   get "/my_teachers" =>"teachers#my_teachers"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
	
	mount_uploader :image, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
before_action :authenticate_user!
 #before_action :set_teacher, only: [:show, :edit, :update, :destroy]
	def new
		@teacher = Teacher.new
   end
       def index
	 	  @teachers= Teacher.all
	     end

      def show 
          @teacher= Teacher.find(params[:id])

        end 
      def create
  
          @teacher = Teacher.new(teacher_params)
          @teacher.user_id = current_user.id

          if @teacher.save

            redirect_to "/teachers/#{@teacher.id}" , notice:'teachers was successfully created' 
            else
             render 'new'
             end		
         end

         def update
          	@teacher= Teacher.find(params[:id])

          	if @teacher.update(teacher_params)

          	  redirect_to "/teachers/#{@teacher.id}",notice:'teachers was successfully updated' 
            else
            	render 'edit'
             end
        end
        def edit
            	@teacher= Teacher.find(params[:id])
            end
          def destroy
        	@teacher=Teacher.find(params[:id])
        	@teacher.destroy
        	redirect_to teachers_path, notice:'teachers was successfully deleted' 
        end

         def my_teachers
         @teachers = Teacher.where(:user_id => current_user.id)
       end
          private

          def teacher_params
           params.require(:teacher).permit(:title, :description,:image)
          end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    ||
    <%= link_to "my Teachers","/my_teachers" %>

  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>

    <%= yield %>
  </body>
</html>

app/views/teachers/edit.html.erb
<h1>Editing teachers</h1>
 <%= form_for @teacher do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 

app/views/teachers/index.html.erb
<h1>Listing teachers</h1>
 <th><%= link_to 'New teachers', new_teacher_path %></th>
<table>
  <tr>
    <th>title</th>
    <th>description</th>
    <th>image</th>
     
  </tr>
    
  <% @teachers.each do |teacher| %>
    <tr>
      <td><%= teacher.title %></td>
      <td><%= teacher.description%></td>
      <td><%= image_tag teacher.image, :height=>"200",:width=>"200" %></td>

      <td><%= link_to 'Show', teacher_path(teacher) %></td>
      <td><%= link_to 'edit', edit_teacher_path(teacher) %></td>
      <td><%= link_to 'delete', teacher_path(teacher),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/teachers/my_teachers.html.erb
<h1>Listing teachers</h1>
 <th><%= link_to 'New teachers', new_teacher_path %></th>
<table>
  <tr>
    <th>title</th>
    <th>description</th>
    <th>image</th>
     
  </tr>
    <tbody>
  <% @teachers.each do |teacher| %>
    <tr>
      <td><%= teacher.title %></td>
      <td><%= teacher.description%></td>
      <td><%= image_tag teacher.image, :height=>"200",:width=>"200" %></td>

      <td><%= link_to 'Show', teacher_path(teacher) %></td>
      <% if current_user.id == teacher.user_id =%>
      <td><%= link_to 'edit', edit_teacher_path(teacher) %></td>
      <td><%= link_to 'delete', teacher_path(teacher),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
        <% end %> 
    </tr>
     </tbody>
  <% end %>
</table>
  <%= link_to 'my_Teachers', new_teacher_path %></th>

app/views/teachers/new.html.erb
<h1> New teachers</h1>
<%= form_for :teacher, url: teachers_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p>
  <strong>title</strong>
  <%= @teacher.title%>
</p>
 
  <strong>description</strong>
  <%= @teacher.description%>
</p>
 
<p>
  <strong>image</strong>
  <%= @teacher.image %>
</p>

<%= link_to 'Back', teachers_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>